---
# Update ESXi OS with latest patch with available latest baseline via vCenter's Life Cycle Manager
- name: "ESXi OS patching - vCenter's Life Cycle Manager ..."
  hosts: all !localhost
  gather_facts: false

  vars_files: # Target variables files
    - "variables/common/set-execution-environment.yml"
    - "variables/play/get-esxi-info.yml"

  tasks:
    - block:
        # Step 1: Pre-Validation for ESXi Patching
        - name: "Step 1 - Pre-Validation for ESXi Patching ..."
          block:
            - name: "Initiate role 'pre_validation' ..." 
              ansible.builtin.include_role:
                name: pre_validation
          delegate-to: localhost

        # Step 2: vLCM Image/Baseline ESXi patching
        - name: "Step 2 - vLCM Image/Baseline ESXi patching ..."
          block:
            - name: "Initiate role 'vlcm_patching' ..." 
              ansible.builtin.include_role:
                name: vlcm_patching
          delegate-to: localhost

        # Step 3: Post-Validation for ESXi Patching
        - name: "Step 3 - Post-Validation for ESXi Patching ..."
          block:
            - name: "Initiate role 'post_validation' ..." 
              ansible.builtin.include_role:
                name: post_validation
          delegate-to: localhost

  # End of play
