---
# post_validation/tasks/main.yml

##############################################################################
# Perform Post‐Validation checks after vLCM remediation
##############################################################################

# 1 - Gather host facts to verify build number
- name: Gather post‐patch host facts
  community.vmware.vmware_host_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ inventory_hostname }}"
    validate_certs: "{{ validate_certs }}"
    show_datacenter: false
  delegate_to: localhost
  register: post_patch_facts

- name: Assert ESXi build matches expected image
  ansible.builtin.assert:
    that:
      - post_patch_facts.ansible_facts.ansible_distribution_build == (cluster_image_version.split('-')[-1])
    fail_msg: "Build {{ post_patch_facts.ansible_facts.ansible_distribution_build }} does not match target {{ cluster_image_version.split('-')[-1] }}"
    success_msg: "Build {{ post_patch_facts.ansible_facts.ansible_distribution_build }} matches target."

# 2 - Exit maintenance mode
- name: Exit Maintenance Mode
  vmware.vmware.esxi_maintenance_mode:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_host_name: "{{ inventory_hostname }}"
    validate_certs: "{{ validate_certs }}"
    enable_maintenance_mode: false
    timeout: 600
  delegate_to: localhost

# 3 - Wait for exit & confirmation
- name: Wait for host to exit Maintenance Mode
  vars:
    tries: 6
    wait: 10
  block:
    - name: Refresh host facts after exit
      community.vmware.vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        esxi_hostname: "{{ inventory_hostname }}"
        validate_certs: "{{ validate_certs }}"
        show_datacenter: false
      delegate_to: localhost
      register: post_exit_facts

    - name: Fail if still in Maintenance Mode
      ansible.builtin.assert:
        that:
          - not post_exit_facts.ansible_facts.ansible_in_maintenance_mode
        fail_msg: "Still in Maintenance Mode."
        success_msg: "Exited Maintenance Mode."
  rescue:
    - name: Retry exit ({{ wait }}s delay, {{ tries }} attempts)
      ansible.builtin.meta: flush_handlers
  retries: "{{ tries }}"
  delay: "{{ wait }}"

# 4 - Verify host health & membership after exit from Maintenance Mode
- name: Verify host connectivity after exit
  ansible.builtin.assert:
    that:
      - post_exit_facts.ansible_facts.ansible_host_connection_state == 'connected'
    fail_msg: "Host lost connectivity after exit."
    success_msg: "Host still connected."

- name: Verify host is still in cluster {{ cluster_name }}
  ansible.builtin.assert:
    that:
      - post_exit_facts.ansible_facts.cluster == cluster_name
    fail_msg: "Host no longer in cluster {{ cluster_name }}."
    success_msg: "Host remains in cluster {{ cluster_name }}."

# 5 - Cleanup the LCM draft (optional)
- name: Remove vLCM draft
  vmware.vmware_rest.esx_settings_clusters_software_drafts:
    vcenter_hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    verify_ssl: "{{ validate_certs }}"
    cluster: "{{ cluster_moid }}"
    draft: "{{ lcm_draft_name }}"
    state: absent
  delegate_to: localhost
  when: cleanup_draft | default(true)

  # End of post_validation/tasks/main.yml
